#################################################################
#                                                               #
#                       Packages/Fitness                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.james_steps:
      icon: fas:walking
    sensor.weight:
      icon: fas:weight
    sensor.tina_steps:
      icon: fas:walking
    sensor.target_weight:
      icon: fas:weight
    sensor.body_fat:
      icon: fas:walking
    sensor.james_bmi:
      icon: fas:walking
    sensor.james_heart_rate:
      icon: fas:heartbeat

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                 Sensors - Fitbit                 #
#                                                  #
####################################################

  - platform: fitbit
    clock_format: 12H
    monitored_resources:
      - "body/weight"
      - "activities/distance"
      - "activities/heart"
      - "activities/steps"
      - "body/bmi"
      - "body/fat"
      - "body/weight"
      - "devices/battery"
      - "sleep/startTime"
      - "sleep/timeInBed"
      
####################################################
#                                                  #
#               Sensors - Google Fit               #
#                                                  #
####################################################

#  - platform: google_fit
#    client_id: !secret google_fit_client_id
#    client_secret: !secret google_fit_client_secret
#    scan_interval: 30
    
####################################################
#                                                  #
#                  Sensors - MQTT                  #
#                                                  #
####################################################

  - platform: mqtt
    name: "James Steps"
    state_topic: "steps/james/huawei"
    
  - platform: mqtt
    name: "James Heart Rate"
    state_topic: "hr/james/huawei"
    unit_of_measurement: "bpm"
    
  - platform: mqtt
    name: "James MiBand Battery"
    device_class: battery
    state_topic: "mibatt/james/huawei"
    unit_of_measurement: "%"
    
  - platform: mqtt
    name: "James MiBand Status"
    state_topic: "mistatus/james/huawei"
    
  - platform: mqtt
    name: "Tina Steps"
    state_topic: "steps/tina/samsung"
    unit_of_measurement: "steps"
    
  - platform: mqtt
    name: "Target Steps"
    state_topic: "target/steps"

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:
      target_weight:
        friendly_name: Target Weight
        entity_id: sensor.weight
        value_template: "{{ 80 - states.sensor.weight.state|int }}"

      james_bmi:
        friendly_name: "James BMI"
        #entity_id: sensor.weight
        value_template: "{{ ((states.sensor.weight.state | float) / (((states.sensor.height.state) | float /100)*((states.sensor.height.state) | float /100))) | round(1)}}"
        unit_of_measurement: 'BMI'
        
      body_fat:
        friendly_name: Body Fat
        #entity_id: sensor.weight
        value_template: "{{ ((1.20 * states.sensor.james_bmi.state|int) + (0.23 * 39) - 16.2)|round }}"
        unit_of_measurement: '%'
        
      average_steps:
        friendly_name: Average Steps
        entity_id: sensor.weekly_steps
        value_template: "{{ (states.sensor.weekly_steps.state|int / 7)|round(0) }}"
        
#################################################################
#                                                               #
#                        Utility Meter                          #
#                                                               #
################################################################# 

utility_meter:
  daily_steps:
    source: sensor.james_steps
    cycle: daily
    
  monthly_steps:
    source: sensor.james_steps
    cycle: monthly
    
  weekly_steps:
    source: sensor.james_steps
    cycle: weekly
